#include "clockreset.h"
#include "core.h"
#include "router.h"
#include "systemc.h"
#include "controller.h"
#include "ROM.h"
#include "pe.h"

#include <sstream>
#include <string>

int sc_main(int argc, char* argv[])
{
    // ============================================================
    // Basic clock/reset signals
    // ============================================================
    sc_signal<bool> clk;
    sc_signal<bool> rst;

    // ============================================================
    // ROM <-> Controller signals
    // ============================================================
    sc_signal<int>   layer_id;
    sc_signal<bool>  layer_id_type;
    sc_signal<bool>  layer_id_valid;

    sc_signal<float> data;
    sc_signal<bool>  data_valid;

    // ============================================================
    // Router input signals
    // router_in_flit[r][p] goes into router r at port p.
    // router_out_ack[r][p] is the ack generated by router r.
    // ============================================================
    sc_signal<sc_lv<34> > router_in_flit[16][5];
    sc_signal<bool>       router_in_req[16][5];
    sc_signal<bool>       router_out_ack[16][5];

    // ============================================================
    // Dummy signals for unused border router ports
    // ============================================================
    sc_signal<sc_lv<34> > dummy_flit[16][5];
    sc_signal<bool>       dummy_req[16][5];
    sc_signal<bool>       dummy_ack[16][5];

    // ============================================================
    // Router LOCAL output -> Core input
    // Used for routers 1 to 15.
    // Router 0 LOCAL is connected to controller.
    // ============================================================
    sc_signal<sc_lv<34> > router_to_core_flit[16];
    sc_signal<bool>       router_to_core_req[16];
    sc_signal<bool>       core_to_router_ack[16];

    // ============================================================
    // Router 0 LOCAL output -> Controller input
    // ============================================================
    sc_signal<sc_lv<34> > router0_to_controller_flit;
    sc_signal<bool>       router0_to_controller_req;
    sc_signal<bool>       controller_to_router0_ack;

    // ============================================================
    // Module declarations
    // ============================================================
    Clock      m_clock("m_clock", 10);
    Reset      m_reset("m_reset", 15);
    ROM        m_rom("m_rom");
    Controller m_controller("m_controller");

    Router* routers[16];
    Core*   cores[16];

    // Create 16 routers
    for (int i = 0; i < 16; i++) {
        std::stringstream router_name;
        router_name << "router_" << i;
        routers[i] = new Router(router_name.str().c_str(), i);

        cores[i] = NULL;
    }

    // Router 0 LOCAL port is used by controller.
    // Core 1 to Core 15 are normal PE cores.
    for (int i = 1; i < 16; i++) {
        std::stringstream core_name;
        core_name << "core_" << i;
        cores[i] = new Core(core_name.str().c_str(), i);
    }

    // ============================================================
    // Clock/reset connections
    // ============================================================
    m_clock.clk(clk);
    m_reset.rst(rst);

    // ============================================================
    // ROM connections
    // Do not edit ROM.h or ROM.cpp.
    // ============================================================
    m_rom.clk(clk);
    m_rom.rst(rst);

    m_rom.layer_id(layer_id);
    m_rom.layer_id_type(layer_id_type);
    m_rom.layer_id_valid(layer_id_valid);

    m_rom.data(data);
    m_rom.data_valid(data_valid);

    // ============================================================
    // Controller connections
    // Controller already has ROM pins and NoC pins.
    // ============================================================
    m_controller.clk(clk);
    m_controller.rst(rst);

    // Controller <-> ROM
    m_controller.layer_id(layer_id);
    m_controller.layer_id_type(layer_id_type);
    m_controller.layer_id_valid(layer_id_valid);

    m_controller.data(data);
    m_controller.data_valid(data_valid);

    // Controller TX -> Router 0 LOCAL input
    m_controller.flit_tx(router_in_flit[0][LOCAL]);
    m_controller.req_tx(router_in_req[0][LOCAL]);
    m_controller.ack_tx(router_out_ack[0][LOCAL]);

    // Router 0 LOCAL output -> Controller RX
    m_controller.flit_rx(router0_to_controller_flit);
    m_controller.req_rx(router0_to_controller_req);
    m_controller.ack_rx(controller_to_router0_ack);

    // ============================================================
    // Router base connections
    // Bind every router input port.
    // ============================================================
    for (int r = 0; r < 16; r++) {
        routers[r]->clk(clk);
        routers[r]->rst(rst);

        for (int p = 0; p < 5; p++) {
            routers[r]->in_flit[p](router_in_flit[r][p]);
            routers[r]->in_req[p](router_in_req[r][p]);
            routers[r]->out_ack[p](router_out_ack[r][p]);
        }
    }

    // ============================================================
    // Router mesh connections
    //
    // Router layout:
    //
    //  0   1   2   3
    //  4   5   6   7
    //  8   9  10  11
    // 12  13  14  15
    //
    // EAST  = router + 1
    // WEST  = router - 1
    // SOUTH = router + 4
    // NORTH = router - 4
    // ============================================================
    for (int r = 0; r < 16; r++) {
        int x = r % 4;
        int y = r / 4;

        // EAST output
        if (x < 3) {
            int nbr = r + 1;
            routers[r]->out_flit[EAST](router_in_flit[nbr][WEST]);
            routers[r]->out_req[EAST](router_in_req[nbr][WEST]);
            routers[r]->in_ack[EAST](router_out_ack[nbr][WEST]);
        } else {
            routers[r]->out_flit[EAST](dummy_flit[r][EAST]);
            routers[r]->out_req[EAST](dummy_req[r][EAST]);
            routers[r]->in_ack[EAST](dummy_ack[r][EAST]);
        }

        // WEST output
        if (x > 0) {
            int nbr = r - 1;
            routers[r]->out_flit[WEST](router_in_flit[nbr][EAST]);
            routers[r]->out_req[WEST](router_in_req[nbr][EAST]);
            routers[r]->in_ack[WEST](router_out_ack[nbr][EAST]);
        } else {
            routers[r]->out_flit[WEST](dummy_flit[r][WEST]);
            routers[r]->out_req[WEST](dummy_req[r][WEST]);
            routers[r]->in_ack[WEST](dummy_ack[r][WEST]);
        }

        // SOUTH output
        if (y < 3) {
            int nbr = r + 4;
            routers[r]->out_flit[SOUTH](router_in_flit[nbr][NORTH]);
            routers[r]->out_req[SOUTH](router_in_req[nbr][NORTH]);
            routers[r]->in_ack[SOUTH](router_out_ack[nbr][NORTH]);
        } else {
            routers[r]->out_flit[SOUTH](dummy_flit[r][SOUTH]);
            routers[r]->out_req[SOUTH](dummy_req[r][SOUTH]);
            routers[r]->in_ack[SOUTH](dummy_ack[r][SOUTH]);
        }

        // NORTH output
        if (y > 0) {
            int nbr = r - 4;
            routers[r]->out_flit[NORTH](router_in_flit[nbr][SOUTH]);
            routers[r]->out_req[NORTH](router_in_req[nbr][SOUTH]);
            routers[r]->in_ack[NORTH](router_out_ack[nbr][SOUTH]);
        } else {
            routers[r]->out_flit[NORTH](dummy_flit[r][NORTH]);
            routers[r]->out_req[NORTH](dummy_req[r][NORTH]);
            routers[r]->in_ack[NORTH](dummy_ack[r][NORTH]);
        }

        // LOCAL output
        if (r == 0) {
            // Router 0 LOCAL output goes to controller
            routers[r]->out_flit[LOCAL](router0_to_controller_flit);
            routers[r]->out_req[LOCAL](router0_to_controller_req);
            routers[r]->in_ack[LOCAL](controller_to_router0_ack);
        } else {
            // Other routers LOCAL output goes to local Core/PE
            routers[r]->out_flit[LOCAL](router_to_core_flit[r]);
            routers[r]->out_req[LOCAL](router_to_core_req[r]);
            routers[r]->in_ack[LOCAL](core_to_router_ack[r]);
        }
    }

    // ============================================================
    // Core connections
    // Core 0 is unused because Router 0 LOCAL is controller.
    // ============================================================
    for (int i = 1; i < 16; i++) {
        cores[i]->clk(clk);
        cores[i]->rst(rst);

        // Router LOCAL output -> Core RX
        cores[i]->flit_rx(router_to_core_flit[i]);
        cores[i]->req_rx(router_to_core_req[i]);
        cores[i]->ack_rx(core_to_router_ack[i]);

        // Core TX -> Router LOCAL input
        cores[i]->flit_tx(router_in_flit[i][LOCAL]);
        cores[i]->req_tx(router_in_req[i][LOCAL]);
        cores[i]->ack_tx(router_out_ack[i][LOCAL]);
    }

    // ============================================================
    // Initialize dummy border ack signals
    // ============================================================
    for (int r = 0; r < 16; r++) {
        for (int p = 0; p < 5; p++) {
            dummy_ack[r][p].write(false);
        }
    }

    // ============================================================
    // Start simulation
    // ============================================================
    // cout << "[MAIN] All modules connected. Starting simulation." << endl;
    sc_start();
    return 0;
}